package projecttracker

class ListProjectsController {

    def index = {
        String page = "";
        page = '<h1>This is index page.</h1>';
        page += '<p>A controller generated by <b>grails create-controller ListProjects</b> command.';
        render page;
    }
}
