package projecttracker

class ListProjectsController {

    def index = {
        String page = "";
        page = '<h1>This is index page.</h1>';
        page += '<p>A controller generated by <b>grails create-controller ListProjects</b> command.';
        render page;
    }

    def current = {
        def projectName = 'Project Tracker Video Tutorials'
        def dueDate = '3/3/2012'
        [project: projectName, date: dueDate]
    }

    def overdue = {
        render 'Order a birthday package!'
    }
}
